In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

import tensorflow as tf

In [3]:

data_loader = sklearn.datasets.load_iris()



In [4]:
data_loader.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
X = data_loader["data"]
Y = data_loader['target']
print(X[120], X.shape)
print(Y, Y.shape)

[6.9 3.2 5.7 2.3] (150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] (150,)


In [5]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

Y = encoder.fit_transform(Y.reshape((-1,1)))


In [18]:
import sklearn.model_selection


X_train, X_test, Y_train, Y_test = sklearn.model_selection.train_test_split(X,Y, test_size=0.2, random_state=42, stratify=Y)

In [7]:
print(X_train.shape)

(120, 4)


In [8]:
print(Y_train, Y_test)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0.

In [9]:
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, Y_train)).batch(16)
test_dataset = tf.data.Dataset.from_tensor_slices((X_test, Y_test)).batch(16)

In [9]:
from model_arch import IrisModel

model = IrisModel(num_classes=3)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics = 'accuracy')


In [10]:
for x,y in train_dataset.take(1):
    print(y)

tf.Tensor(
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(16, 3), dtype=float64)


In [11]:
model.fit(train_dataset, epochs = 100)

Epoch 1/100
8/8 [==============================] - 1s 3ms/step - loss: 1.0699 - accuracy: 0.3500
Epoch 2/100
8/8 [==============================] - 0s 3ms/step - loss: 1.0426 - accuracy: 0.3917
Epoch 3/100
8/8 [==============================] - 0s 2ms/step - loss: 1.0196 - accuracy: 0.4917
Epoch 4/100
8/8 [==============================] - 0s 3ms/step - loss: 0.9991 - accuracy: 0.5667
Epoch 5/100
8/8 [==============================] - 0s 3ms/step - loss: 0.9811 - accuracy: 0.6417
Epoch 6/100
8/8 [==============================] - 0s 3ms/step - loss: 0.9640 - accuracy: 0.6500
Epoch 7/100
8/8 [==============================] - 0s 2ms/step - loss: 0.9463 - accuracy: 0.6500
Epoch 8/100
8/8 [==============================] - 0s 6ms/step - loss: 0.9276 - accuracy: 0.6583
Epoch 9/100
8/8 [==============================] - 0s 3ms/step - loss: 0.9078 - accuracy: 0.6667
Epoch 10/100
8/8 [==============================] - 0s 3ms/step - loss: 0.8869 - accuracy: 0.6667
Epoch 11/100
8/8 [===========

In [12]:
model.evaluate(test_dataset)

2/2 [==============================] - 0s 11ms/step - loss: 0.1729 - accuracy: 0.9667


[0.1729421615600586, 0.9666666388511658]

In [37]:
model.save_weights("iris_classifier_1.h5")

In [24]:
from sklearn.metrics import classification_report
Y_pred = model.predict(test_dataset)


2/2 [==============================] - 0s 3ms/step


In [25]:
Y_pred_l = [np.argmax(i) for i in Y_pred]

In [31]:
Y_test_l = [np.argmax(i) for i in Y_test]

In [32]:
print(Y_pred_l)
print(Y_test_l)

[2, 0, 1, 1, 2, 1, 2, 2, 0, 2, 0, 0, 0, 1, 2, 2, 2, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 2, 0, 2]
[2, 0, 1, 1, 2, 1, 2, 2, 0, 1, 0, 0, 0, 1, 2, 2, 2, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 2, 0, 2]


In [33]:
print(classification_report(Y_pred_l, Y_test_l))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      1.00      0.95         9
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [21]:
Y_pred = model.predict(X_test)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [23]:
import pickle

In [24]:
with open('iris_mod.pkl', 'wb') as f:
    pickle.dump(model, f)   

In [10]:
print(np.__version__)

1.26.4
